import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Top from "./components/Header/Top";
import Navbar from "./components/Header/Navbar";
import Footer from "./components/Footer/Footer";
import { CartProvider } from "./context/cart";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <CartProvider>
        <Top/>
        <Navbar/>
        {children}
        <ToastContainer />
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
